### ISSUE TITLE
option for ArchiveJSONViewLoader to extract HTTP body 

### ISSUE THREAD

**Issue by rjoberon** [internetarchive/archive-commons#8]
Is it planned to include an option for the [ArchiveJSONViewLoader](https://github.com/internetarchive/archive-commons/blob/master/archive-commons/src/main/java/org/archive/hadoop/ArchiveJSONViewLoader.java) to extract the complete HTTP body such that it can be analysed with Pig, too?

**Comment by nlevitt** [comment]
Hello... you know archive-commons is obsolete right? See https://github.com/internetarchive/archive-commons/blob/master/OBSOLETE

**Comment by rjoberon** [comment]
Well, yes. But I did not find an issue tracker for [ia-web-commons](https://github.com/internetarchive/ia-web-commons) which is the relevant project now.

**Comment by nlevitt** [comment]
Ah, sorry! I enabled issue tracking to that repo.

**Comment by rjoberon** [comment]
Thanks. I [moved the issue](https://github.com/internetarchive/ia-web-commons/issues/2) to that tracker.
